# Base configs
baseurl: "https://nightshift1001.github.io/Karolina-Gasiorowska/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Karolina Gasiorowska"
author: "Karolina Gasiorowska"

title: "Karolina Gasiorowska"
subtitle: "by Karolina Gasiorowska"
social_urls:
  youtube: "https://www.youtube.com/channel/UC4sHSkIs5wNrHCg05Yuj2pA"
  instagram: "https://www.instagram.com/kvrogvsio/"
