# Base configs
baseurl: "http://thearchailect.me/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "The Archailect Portfolio"
subtitle: "test"
author: "The Archailect"
header:
 title: "3D concept art and hardsurface modeling"
 subtitle: "by The Archailect"
footer:
 name: ""
 bio: ""
 github: ""
web_design: ""
social_urls:
  twitter: "https://www.twitter.com/thearchailect"
  instagram: "https://www.instagram.com/thearchailect"