# Base configs
baseurl: "http://thearchailect.me/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "The Archailect Portfolio"
author: "The Archailect"

title: "The Archailect"
subtitle: "by The Archailect"
social_urls:
  youtube: "https://www.youtube.com/channel/UC2Of9mGeJqlWjFm15TSKLGQ"
  twitter: "https://www.twitter.com/thearchailect"
  instagram: "https://www.instagram.com/thearchailect"
